name: unpub
description: A new Flutter project.

version: 1.0.0+2

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.0
  cupertino_icons: ^0.1.2
  json_annotation: ^2.0.0
  intl: ^0.15.7
  path_provider: ^0.5.0
  shared_preferences: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.1.2
  json_serializable: ^2.0.0 

flutter:
  uses-material-design: true

  